name: Build Check

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ ".github/**" ]
  pull_request:
    branches: [ "master" ]
    paths-ignore: [ ".github/**" ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: 17
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace
