name: SonarQube analysis

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'gradle/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'gradle/**'
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: app/src
          args:
            -Dsonar.projectKey=Keeper
            -Dsonar.projectName=Keeper
            -Dsonar.sources=main/kotlin
            -Dsonar.tests=androidTest/kotlin,test/kotlin
